### ISSUE TITLE
Need to add "USER root" before RUN command. 

### ISSUE THREAD

**Issue by csho** [mtakamot/hadoop-hive-spark-docker#2]
https://github.com/mtakamot/hadoop-hive-spark-docker/blob/626b0d0fdef1a38678d44b5a3b910e187f245341/base/Dockerfile#L108

and USER $USERNAME after. 

Or, docker build command would failed reporting:"ln: failed to create hard link '/opt/spark/conf/workers' => '/opt/hadoop/etc/hadoop/workers': Operation not permitted"

**Comment by mtakamot** [comment]
In my environment, successfully build image.
If you modify Dockerfile, I do not support that.

**Comment by csho** [comment]
No, I do not modify any thing. System : centos 7.6 , Docker version 20.10.14

**Comment by mtakamot** [comment]
It could be reproduced in a Linux environment. Fix.
